# Generated by Django 4.1.3 on 2022-11-29 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("dni", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                ("promedio_notas", models.FloatField()),
                ("asisitencia", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Cargo1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_cargo", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Profesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("dni", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                ("salario", models.FloatField(null=True)),
                ("horas_trabajo", models.IntegerField()),
            ],
            options={
                "verbose_name_plural": "profesores",
                "db_table": "profesor",
            },
        ),
        migrations.CreateModel(
            name="Salon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("aula", models.CharField(max_length=30)),
                ("hora_entrada", models.TimeField(auto_now=True)),
                (
                    "id_profesor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="escuela.profesor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Directivo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("dni", models.CharField(max_length=10)),
                ("email", models.EmailField(max_length=254)),
                (
                    "cargo",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="escuela.cargo1",
                    ),
                ),
            ],
            options={
                "db_table": "dire",
            },
        ),
    ]
