# Generated by Django 4.1.3 on 2022-11-29 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escuela", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SuperAlumno",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("escuela.alumno",),
        ),
        migrations.AlterField(
            model_name="salon",
            name="aula",
            field=models.CharField(max_length=2),
        ),
    ]
