# Generated by Django 4.1.3 on 2022-11-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escuela", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("dni", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("salario", models.FloatField()),
                ("asistencia", models.DateTimeField()),
                ("registro_notas", models.IntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
