# Generated by Django 4.1.3 on 2022-11-29 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alumno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("dni", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("promedio_notas", models.FloatField(max_length=4)),
                ("asistencia", models.IntegerField()),
            ],
            options={
                "db_table": "alumnos",
            },
        ),
        migrations.CreateModel(
            name="Profesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("dni", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("sueldo", models.FloatField()),
                ("horario", models.DateTimeField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SuperAlumno",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("usuario.alumno",),
        ),
    ]
