# Generated by Django 4.1.3 on 2022-11-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=30, null=True)),
                ("description", models.TextField(max_length=50)),
                ("is_activate", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "blogs",
            },
        ),
    ]
