# Generated by Django 4.1.3 on 2022-11-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="autor",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
