# Generated by Django 4.1.3 on 2022-12-01 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vitrina", "0002_alter_book_table"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Book",
            new_name="Books",
        ),
    ]
